title: Jo A jin blog
author: waiajin.io
email: ajinjo@waikorea.com
description: >-
  예시 샘플 홈페이지 입니다.
baseurl: "/ubuild-jekyll" # the subpath of your site, e.g. /blog
url: "" # your site's origin, e.g. https://waiajin.io

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

plugins:
  - jekyll-feed
  - jekyll-menus
